[project]
name = "lab-uv1-libama"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "p-libamadubos-ece", email = "pauldavid.libamadubos@edu.ece.fr" }
]
requires-python = ">=3.13"
dependencies = [
    "faker>=40.40.0",
]

[project.scripts]
dataset-users = "lab_uv1_libama.dataset_users:main"
dataset-orders = "lab_uv1_libama.dataset_orders:main"

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"
